### ISSUE TITLE
No .xpr found

### ISSUE THREAD

**Issue by Neelam96** [Digilent/Nexys-Video-DMA#1]
I have extracted the *.zip file from your release page for 2018.2 but the extracted folder has no .xpr file for project.

**Comment by Neelam96** [comment]
Can anyone please explain how to use this project because there was no .xpr file when I extracted the repo?

**Comment by moinocencio** [comment]
Don't know if it still helps, but if you get the [Release](https://github.com/Digilent/Nexys-Video-DMA/releases), the **.xpr** is under _vivado_proj_

**Comment by Neelam96** [comment]
Thanks
Found it now
